### ISSUE TITLE
No section mw_server

### ISSUE THREAD

**Issue by sid9553** [ari/moneyworks-cli#1]
Hi there,

I got this error on trying to run your script. I'm thinking its not finding the config file for some reason. I've placed it in the same directory as the script. Is this correct?

Regards
Ahmad

**Comment by ari** [comment]
What error?

**Comment by sid9553** [comment]
The error in the title. No section mw_server.

**Comment by ari** [comment]
Without a stack trace or more information, I've got no idea. Happy to help, but I can't read your mind about what you executed how you set it up, what you were trying to do or what line of code you hit with that error.

**Comment by rallen2010** [comment]
Having had a similar error today, the "No section mw_server" error occurs when it can't parse the mw.ini file.  This can be because there is no mw.ini file (or at least not in the search path).  The Configuration Parser is designed not to throw an error if it can't find a file (to allow optional config files) -- so you won't see a file opening error -- just an error that the section heading is missing.
In my case, the problem was that I didn't have the mw.ini file in the correct search path -- so it couldn't find it.
Hope this helps shoe else having the same struggle in the future.

**Comment by ari** [comment]
Thanks. Would you like to contribute a patch that makes the parser throw a more informative error if the config is missing?

**Comment by ari** [comment]
Now we throw an error if the config is missing.
